name: link_metadata
description: "A Dart package for extracting Open Graph metadata, images, and favicons from URLs."
version: 0.0.1
homepage: https://github.com/ekakshjanweja/link_metadata

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.5.0

dev_dependencies:
  lints: ^5.0.0
